server.port=5000


# PostgreSQL DataSource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/traini8
spring.datasource.username=postgres
spring.datasource.password=@Suraj2216

# JPA & Hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Enable SQL logging
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
